before_script:
  - export PROJECT_DIR=`pwd`
  - apt-get -y --no-install-recommends --force-yes -o Dpkg::Options::='--force-confdef' -o Dpkg::Options::='--force-confnew' install python-setuptools
  - git clone https://github.com/s3tools/s3cmd /tmp/s3cmd
  - cd /tmp/s3cmd && python setup.py install && cd $PROJECT_DIR
  - echo "[default]" > ~/.s3cfg
  - echo "access_key =" >> ~/.s3cfg
  - echo "secret_key =" >> ~/.s3cfg
  - echo "security_token =" >> ~/.s3cfg
  - ssh-keyscan -t rsa git.in.moodle.com >> ~/.ssh/known_hosts
  - s3cmd get s3://moodlecloud-ci/moodlecloud-cibot.pem ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - git config --global user.email "noreply@moodlecloud.com"
  - git config --global user.name "MoodleCloud Git Octopus"
  - git clone https://github.com/lesfurets/git-octopus /tmp/git-octopus
  - cd /tmp/git-octopus && make install && cd $PROJECT_DIR

variables:
  MOODLE_VERSION: "3.2"
  PUSH_REPO: "git@git.in.moodle.com:hosting/moodle.git"
  FREE_BRANCHES: "origin/CLOUD-$MOODLE_VERSION/FEATURE-bbb origin/CLOUD-$MOODLE_VERSION/FEATURE-cache origin/CLOUD-$MOODLE_VERSION/FEATURE-crontest origin/CLOUD-$MOODLE_VERSION/FEATURE-email-sender origin/CLOUD-$MOODLE_VERSION/FEATURE-moodlecloud origin/CLOUD-$MOODLE_VERSION/FEATURE-noupgrade origin/CLOUD-$MOODLE_VERSION/FEATURE-S3 origin/CLOUD-$MOODLE_VERSION/FEATURE-logging origin/CLOUD-$MOODLE_VERSION/FEATURE-user_update"
  SCHOOL_BRANCHES: "origin/CLOUD-$MOODLE_VERSION/FEATURE-bbb origin/CLOUD-$MOODLE_VERSION/FEATURE-cache origin/CLOUD-$MOODLE_VERSION/FEATURE-crontest origin/CLOUD-$MOODLE_VERSION/FEATURE-email-sender origin/CLOUD-$MOODLE_VERSION/FEATURE-moodlecloud origin/CLOUD-$MOODLE_VERSION/FEATURE-noupgrade origin/CLOUD-$MOODLE_VERSION/FEATURE-S3 origin/CLOUD-$MOODLE_VERSION/FEATURE-logging origin/CLOUD-$MOODLE_VERSION/FEATURE-user_update origin/CLOUD-$MOODLE_VERSION/FEATURE-atto_chemistry origin/CLOUD-$MOODLE_VERSION/FEATURE-atto_count origin/CLOUD-$MOODLE_VERSION/FEATURE-block_xp origin/CLOUD-$MOODLE_VERSION/FEATURE-checklist origin/CLOUD-$MOODLE_VERSION/FEATURE-mod_attendance origin/CLOUD-$MOODLE_VERSION/FEATURE-mod_choicegroup origin/CLOUD-$MOODLE_VERSION/FEATURE-mod_quizgame origin/CLOUD-$MOODLE_VERSION/FEATURE-theme_school origin/CLOUD-$MOODLE_VERSION/FEATURE-mod_customcert"
  TESTING_BRANCHES: "origin/CLOUD-$MOODLE_VERSION/FEATURE-bbb origin/CLOUD-$MOODLE_VERSION/FEATURE-cache origin/CLOUD-$MOODLE_VERSION/FEATURE-crontest origin/CLOUD-$MOODLE_VERSION/FEATURE-email-sender origin/CLOUD-$MOODLE_VERSION/FEATURE-moodlecloud origin/CLOUD-$MOODLE_VERSION/FEATURE-noupgrade origin/CLOUD-$MOODLE_VERSION/FEATURE-S3 origin/CLOUD-$MOODLE_VERSION/FEATURE-logging origin/CLOUD-$MOODLE_VERSION/FEATURE-user_update origin/CLOUD-$MOODLE_VERSION/FEATURE-atto_chemistry origin/CLOUD-$MOODLE_VERSION/FEATURE-atto_count origin/CLOUD-$MOODLE_VERSION/FEATURE-block_xp origin/CLOUD-$MOODLE_VERSION/FEATURE-checklist origin/CLOUD-$MOODLE_VERSION/FEATURE-mod_attendance origin/CLOUD-$MOODLE_VERSION/FEATURE-mod_choicegroup origin/CLOUD-$MOODLE_VERSION/FEATURE-mod_quizgame origin/CLOUD-$MOODLE_VERSION/FEATURE-theme_school origin/CLOUD-$MOODLE_VERSION/FEATURE-wiris origin/CLOUD-$MOODLE_VERSION/FEATURE-mod_customcert"

stages:
 - build

merge_free:
  stage: build
  tags:
    - php
  script:
    - git remote set-url --push origin $PUSH_REPO
    - git checkout CLOUD-$MOODLE_VERSION/base
    - git reset --hard origin/CLOUD-$MOODLE_VERSION/base
    - git octopus $FREE_BRANCHES origin/CLOUD-$MOODLE_VERSION/base
    - if [ -e .gitlab-ci.yml ]; then git rm .gitlab-ci.yml; git commit -m "Removing gitlab-ci.yml"; fi
    - git push --force origin +HEAD:FREE-$MOODLE_VERSION/octopus-staging
    - git reset --hard origin/CLOUD-$MOODLE_VERSION/base
  allow_failure: false

merge_school:
  stage: build
  tags:
    - php
  script:
    - git remote set-url --push origin $PUSH_REPO
    - git checkout CLOUD-$MOODLE_VERSION/base
    - git reset --hard origin/CLOUD-$MOODLE_VERSION/base
    - git octopus $SCHOOL_BRANCHES origin/CLOUD-$MOODLE_VERSION/base
    - if [ -e .gitlab-ci.yml ]; then git rm .gitlab-ci.yml; git commit -m "Removing gitlab-ci.yml"; fi
    - git push $PUSH_REPO +HEAD:SCHOOL-$MOODLE_VERSION/octopus-staging
    - git reset --hard origin/CLOUD-$MOODLE_VERSION/base
  allow_failure: false

merge_testing_school:
  stage: build
  tags:
    - php
  script:
    - git remote set-url --push origin $PUSH_REPO
    - git checkout CLOUD-$MOODLE_VERSION/base
    - git reset --hard origin/CLOUD-$MOODLE_VERSION/base
    - git octopus $TESTING_BRANCHES origin/CLOUD-$MOODLE_VERSION/base
    - if [ -e .gitlab-ci.yml ]; then git rm .gitlab-ci.yml; git commit -m "Removing gitlab-ci.yml"; fi
    - git push $PUSH_REPO +HEAD:SCHOOL-$MOODLE_VERSION/octopus-testing
    - git reset --hard origin/CLOUD-$MOODLE_VERSION/base
  allow_failure: false
